settings:
  disable-pickup-in-god: true
  disable-pickup-in-fly: true
  disable-block-break-in-god: true
  disable-block-break-in-fly: true
  disable-block-place-in-god: true
  disable-block-place-in-fly: true
  disable-drop-item-in-god: true
  disable-drop-item-in-fly: true
  disable-pvp-in-god: true
  disable-pvp-in-fly: true
  disable-hit-mob-in-god: true
  disable-hit-mob-in-fly: true
  disable-chest-in-god: true
  disable-chest-in-fly: true
  disable-containers-in-god: true
  disable-containers-in-fly: true
  disable-interact-bow-in-god: true
  disable-interact-bow-in-fly: true
  disable-interact-crystal-in-god: true
  disable-interact-crystal-in-fly: true
  disable-interact-flint-in-god: true
  disable-interact-flint-in-fly: true
  disable-interact-enderchest-in-god: true
  disable-interact-enderchest-in-fly: true
  disable-interact-shulker-in-god: true
  disable-interact-shulker-in-fly: true
  disable-interact-entities-in-god: true
  disable-interact-entities-in-fly: true
  disable-projectiles-in-god: true
  disable-projectiles-in-fly: true
  disable-vehicles-in-god: true
  disable-vehicles-in-fly: true
  disable-spawn-eggs-in-god: true
  disable-spawn-eggs-in-fly: true
  check-updates: true

messages:
  prefix: "&6[&lServer&6] &r"
