settings:
  disable-pickup-in-god: true
  disable-pickup-in-fly: true
  check-updates: true

messages:
  prefix: "§x§B§3§6§7§1§2§lL§x§B§5§6§A§1§6§la§x§B§6§6§C§1§9§ls§x§B§8§6§F§1§D§lt§x§B§9§7§1§2§0§lL§x§B§B§7§4§2§4§li§x§B§C§7§6§2§7§ln§x§B§E§7§9§2§B§le§x§B§F§7§B§2§F§lC§x§C§1§7§E§3§2§lo§x§C§2§8§0§3§6§ln§x§C§4§8§3§3§9§lt§x§C§5§8§5§3§D§lr§x§C§7§8§8§4§0§lo§x§C§8§8§A§4§4§ll "
